# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/mist-ast", "crates/mist-tokens", "crates/mist-syntax"]

[workspace.package]
authors = ["Colton D. <colton@donn.io>"]
edition = "2021"

[workspace.dependencies]
miette = "=5.4"
num = "=0.4"
once_cell = "=1.16"
pretty_assertions = "=1.3"
rowan = "=0.15"
rstest = "=0.15"
thiserror = "=1.0"
tracing = "=0.1"

mist-ast = { path = "crates/mist-ast" }
mist-syntax = { path = "crates/mist-syntax" }
mist-tokens = { path = "crates/mist-tokens" }

[workspace.dependencies.salsa]
git = "https://github.com/salsa-rs/salsa"
package = "salsa-2022"
